// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbtioAvLVsyM_i3KkHD0hjhS2XWRqXyis',
    appId: '1:627291303328:web:8e48d301ba97aebf3c08c5',
    messagingSenderId: '627291303328',
    projectId: 'voice-journal-e3080',
    authDomain: 'voice-journal-e3080.firebaseapp.com',
    storageBucket: 'voice-journal-e3080.appspot.com',
    measurementId: 'G-YBT1FXQYCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArplQVUmcX6gAaj2y_CXVqBV0bluVNCS8',
    appId: '1:627291303328:android:1b90a63deadb0e2a3c08c5',
    messagingSenderId: '627291303328',
    projectId: 'voice-journal-e3080',
    storageBucket: 'voice-journal-e3080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbsWj5iMN7QCOPsBxPh9f8O2OP4DoJVhw',
    appId: '1:627291303328:ios:b3aa8c42a6e527cd3c08c5',
    messagingSenderId: '627291303328',
    projectId: 'voice-journal-e3080',
    storageBucket: 'voice-journal-e3080.appspot.com',
    iosClientId: '627291303328-io4qvsevqtasf7r5ucchpprurg7oqi0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.nakuskiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbsWj5iMN7QCOPsBxPh9f8O2OP4DoJVhw',
    appId: '1:627291303328:ios:6fb83e78266bf2c63c08c5',
    messagingSenderId: '627291303328',
    projectId: 'voice-journal-e3080',
    storageBucket: 'voice-journal-e3080.appspot.com',
    iosClientId: '627291303328-i2b7gkp68qcjpcdq6dhutjm1aujn3r96.apps.googleusercontent.com',
    iosBundleId: 'com.example.nakuskiaApp.RunnerTests',
  );
}
